### PR TITLE
Update JsonFileTarget.php

### PR DESCRIPTION
**Pull request by wapmorgan**
Use yii2's `LogTarget::getTime()` to format date because it can join microtime to timestamp.

### CODE REVIEW

**Comment by wapmorgan** [comment]
So what about merging?

**Comment by petrabarus** [comment]
Is this backwards compat with past Yii version?

**Comment by wapmorgan** [comment]
`Target::getTime()` is available since 2017-10-18 (https://github.com/yiisoft/yii2/blame/master/framework/log/Target.php#L395-L401). That's 2.0.13 or 2.0.14 framework version.

**Comment by wapmorgan** [comment]
What about release?

**Pull request merged**
